services:
    football-inpaint-train-lora:
        image: football-inpaint-train-lora
        container_name: football-inpaint-train-lora
        restart: always
        build:
            context: .
            network: host
            dockerfile: Dockerfile
        ports:
            - "6002:80"
            - "5002:5002"
        volumes:
            - ./frontend/var/log:/var/log/nginx
            - ./backend/models:/usr/share/nginx/html/backend/models
